services:
    forumhulp.realpostcount.listener:
        class: forumhulp\realpostcount\event\listener
        arguments:
            - @config
            - @controller.helper
            - @user
            - @template
            - @dbal.conn
        tags:
            - { name: event.listener }